# Generated by Django 2.2.10 on 2021-03-07 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(max_length=200, unique=True)),
                ('file_description', models.CharField(max_length=1000)),
                ('file_creation_date', models.DateField(blank=True, default=None, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=200)),
                ('section_code', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PUC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puc_date', models.DateField(blank=True, default=None, null=True)),
                ('puc_regarding', models.CharField(max_length=2000, null=True)),
                ('priority', models.CharField(max_length=50, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.File')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Section')),
            ],
        ),
        migrations.CreateModel(
            name='FileMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('put_up_before', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=2000, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=50, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.File')),
                ('puc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PUC')),
                ('put_up_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Section')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Section'),
        ),
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Section'),
        ),
    ]
