# Generated by Django 2.2.10 on 2021-03-19 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210320_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(blank=True, default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='filemovement',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 20, 0, 26, 48, 241632)),
        ),
        migrations.AlterField(
            model_name='filemovement',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 20, 0, 26, 48, 241632)),
        ),
    ]
