# Generated by Django 2.2.10 on 2021-03-19 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210320_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemovement',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 20, 0, 27, 59, 364992)),
        ),
        migrations.AlterField(
            model_name='filemovement',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 20, 0, 27, 59, 365992)),
        ),
    ]
