# Generated by Django 2.2.10 on 2021-03-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210323_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('user_control', models.IntegerField(null=True)),
            ],
        ),
    ]
