# Generated by Django 2.2.10 on 2021-04-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210426_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('rate_per_gram', models.IntegerField(null=True)),
                ('charge_per_gram', models.IntegerField(null=True)),
                ('making_charge', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ItemList')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order')),
            ],
        ),
    ]
