# Generated by Django 2.2.10 on 2021-04-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='item_availability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemlist',
            name='item_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
